#!/usr/bin/env python3
"""KUA graph integration — connect newly-filed notes into the vault graph.

For each note path given (vault-relative, e.g. "AI/01-concepts/foo.md"):
  1. Append a marked `## Related` section: a Hub link to the note's MOC plus
     up to 5 tag-similar sibling notes (IDF-weighted shared tags).
  2. Register the note in its Hub MOC (under "## Recent additions") so the MOC
     stays current. Creates the MOC if it does not exist (no broken hub links).

Idempotent: skips notes that already carry the auto-related marker, and never
double-lists a note in a MOC. Run AFTER notes are filed (Step 4 / Step 6).

Usage:
  python3 kua_graph_integrate.py "AI/01-concepts/foo.md" "Cooking/01-recipes/bar.md" ...
"""
import os, re, sys, math
from collections import Counter, defaultdict

VAULT = "/Users/ashleydsouza/Library/Mobile Documents/iCloud~md~obsidian/Documents/ai-knowledge-vault"
RELATED_MARK = "<!-- auto-related: generated by Claude, safe to edit/remove -->"
MOC_MARK = "<!-- auto-moc: generated by Claude, safe to edit/remove -->"
# tags too broad/process-y to drive sibling similarity
SKIP_SIM = {"knowledge-extractor", "incomplete-capture", "twitter", "other", "x",
            "untitled", "tweet", "linkedin", "substack", "newsletter", "email",
            "moc", "home", "inbox", "draft", "todo", "ai", "tech"}
frontmatter_re = re.compile(r"^---\n(.*?)\n---", re.DOTALL)


def get_tags(text):
    m = frontmatter_re.match(text); tags = set()
    if m:
        fm = m.group(1)
        for line in fm.split("\n"):
            mm = re.match(r'^tags?:\s*(.*)$', line)
            if mm and mm.group(1).strip().startswith('['):
                for t in mm.group(1).strip()[1:].rstrip(']').split(','):
                    t = t.strip().strip('"').strip("'")
                    if t: tags.add(t)
        block = re.search(r'(?m)^tags?:\s*\n((?:\s*-\s*.+\n?)+)', fm)
        if block:
            for l in block.group(1).split("\n"):
                t = re.sub(r'^\s*-\s*', '', l).strip().strip('"').strip("'")
                if t: tags.add(t)
    for mm in re.finditer(r"(?:^|\s)#([A-Za-z0-9_\-/]+)", text):
        tags.add(mm.group(1))
    return {t.lower().lstrip("#") for t in tags}


def hub_for(rel):
    """Return (moc_name, moc_relpath) for a note's hub MOC."""
    parts = rel.split("/")
    top = parts[0]
    if top == "AI":
        if len(parts) > 2:
            nice = re.sub(r"^\d+-", "", parts[1]).replace("-", " ").title()
            name = f"AI {nice} MOC"
            return name, f"AI/{parts[1]}/{name}.md"
        return "AI MOC", "AI/AI MOC.md"
    return f"{top} MOC", f"{top}/{top} MOC.md"


def ensure_moc(moc_rel, moc_name):
    full = os.path.join(VAULT, moc_rel)
    if os.path.exists(full):
        return
    os.makedirs(os.path.dirname(full), exist_ok=True)
    body = ("---\ntags: [moc]\ntype: moc\n---\n\n" + MOC_MARK + "\n\n"
            f"# {moc_name}\n\n"
            "> Map of Content — auto-generated hub. Links every note in this area so they connect in the graph.\n")
    with open(full, "w", encoding="utf-8") as f:
        f.write(body)


def register_in_moc(moc_rel, moc_name, basename):
    full = os.path.join(VAULT, moc_rel)
    with open(full, "r", encoding="utf-8", errors="replace") as f:
        text = f.read()
    if f"[[{basename}]]" in text:
        return False
    if "## Recent additions" not in text:
        text = text.rstrip("\n") + "\n\n## Recent additions\n"
    text = text.rstrip("\n") + f"\n- [[{basename}]]\n"
    with open(full, "w", encoding="utf-8") as f:
        f.write(text)
    return True


def build_index():
    notes = []  # (rel, basename, tags)
    for root, dirs, files in os.walk(VAULT):
        dirs[:] = [d for d in dirs if not d.startswith('.')]
        for f in files:
            if not f.endswith(".md"):
                continue
            base = os.path.splitext(f)[0]
            if base.endswith(" MOC") or base in {"Home", "README", "CLAUDE"}:
                continue
            rel = os.path.relpath(os.path.join(root, f), VAULT)
            try:
                txt = open(os.path.join(root, f), encoding="utf-8", errors="replace").read()
            except Exception:
                continue
            notes.append((rel, base, get_tags(txt) - SKIP_SIM))
    N = max(len(notes), 1)
    df = Counter()
    for _, _, tags in notes:
        for t in tags:
            df[t] += 1
    idf = {t: math.log(N / c) for t, c in df.items()}
    by_tag = defaultdict(list)
    for i, (_, _, tags) in enumerate(notes):
        for t in tags:
            by_tag[t].append(i)
    return notes, df, idf, by_tag, N


def siblings_for(rel, notes, df, idf, by_tag, N, k=5):
    tags = None
    for r, b, tg in notes:
        if r == rel:
            tags = tg; break
    if not tags:
        return []
    scores = Counter()
    for t in tags:
        if df.get(t, 0) > N * 0.5:
            continue
        for j in by_tag.get(t, ()):
            if notes[j][0] != rel:
                scores[j] += idf[t]
    return [notes[j][1] for j, _ in scores.most_common(k)]


def integrate(rel, notes, df, idf, by_tag, N):
    full = os.path.join(VAULT, rel)
    if not os.path.exists(full):
        return f"skip (missing): {rel}"
    with open(full, "r", encoding="utf-8", errors="replace") as f:
        text = f.read()
    base = os.path.splitext(os.path.basename(rel))[0]
    moc_name, moc_rel = hub_for(rel)
    ensure_moc(moc_rel, moc_name)
    registered = register_in_moc(moc_rel, moc_name, base)
    if RELATED_MARK in text:
        return f"hub-only (already has Related): {rel}"
    sibs = siblings_for(rel, notes, df, idf, by_tag, N)
    block = ["", "## Related", RELATED_MARK, f"- Hub: [[{moc_name}]]"]
    seen = {moc_name, base}
    for s in sibs:
        if s not in seen:
            block.append(f"- [[{s}]]")
            seen.add(s)
    with open(full, "w", encoding="utf-8") as f:
        f.write(text.rstrip("\n") + "\n" + "\n".join(block) + "\n")
    return f"linked ({len(seen) - 1} links{', +MOC' if registered else ''}): {rel}"


def main():
    targets = sys.argv[1:]
    if not targets:
        print("No note paths given. Usage: kua_graph_integrate.py <vault-rel-path> ...")
        return
    notes, df, idf, by_tag, N = build_index()
    for rel in targets:
        print(integrate(rel.strip().lstrip("/"), notes, df, idf, by_tag, N))


if __name__ == "__main__":
    main()
